{% set version = '0.1-10' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assotester
  version: {{ version|replace("-", "_") }}

source:
  fn: AssotesteR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/AssotesteR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/AssotesteR/AssotesteR_{{ version }}.tar.gz
  sha256: 9ca548dd1eee059e311a74ccd8455231f81c7461e6e31ca567f9ee741e8dda2b

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mvtnorm

  run:
    - r-base
    - r-mvtnorm

test:
  commands:
    - $R -e "library('AssotesteR')"  # [not win]
    - "\"%R%\" -e \"library('AssotesteR')\""  # [win]

about:
  home: http://www.gastonsanchez.com
  license: GPL (>= 3)
  summary: R package with statistical tests and methods for genetic association studies with
    emphasis on rare variants and binary (dichotomous) traits
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
