# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "4YFelmBseFm/H8ZLabIUwXeOMQDRfqx+q9ywr4k+VJK9Nr/zdGENAuOiQT+es6aQ3HXiuKAqfDhiKhDF8dsBrtfZkO097hzva8dvSZjjv8Jlw7c2QrFkbrtNFD7ASw+gYec8BeD0/aIh3KZrmfF5sZ7sDx6/MJicn2ZYBy/4oZG8uXbFmfMA5pTnuuyJrJRvYmpQCav/Fo9sZSit3VOEC5Fp3uIkY+zbBQlEJQJdbLkFOUHy6VBrCzmVM7DHM21x62KdEsP9est8Oq9R20SV1PSxIOxo7PGLkaGFp5TsY0P58DfaiY32WXOgGcUEHehJEDHrUfwoLXLDBl0OPI9nMxFtMtetFkyJZZl95f+KuxOtfYSWzi3VL03r2CDo3GGVT+awoqf4K1BNbaqdu74bb6YAeXSRUzGZFhF7IfGX8BWrWLet/Qh46O/5/02G/m7R31A0D3iq8xbTs2fyE9jDUcA3xIQ5sAXeQzExH3dfomdDC9SMTUzUwS6weacPDDTDmqOWJVSR+90X+GQpv5qqmw1juydIdtUaeLccp+4TV/j9W9VhK8wBLxxAU5C1UAenlsJ5RpZt7GVlti1z9V3epFEwo/PM/YqzgPxdTD2+ZyfSS7c3KG/cseBaUqYOZP+Zaa9s0za+9bhAgxC5rg/XfXu0OCWdCxWhLm3T5/oqvto="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
