travis:
  secure:
    BINSTAR_TOKEN: 5BjoSElqNdOEmAKnZ1hnZOZ6RfVDxai6x3XzAim53pvn3EdIFCAFmkJ9PDgojGCvrrXzIQ9Z0oIrSOKxCOqUnEhEdISNL19VAaOHR2nzMAQOepI53h536ks2EomzvWb9mzzy/ZsU4YXjr2r97DYJNYz3je5n0/YLfC7jA4Nc/9HCcEL6yZxFu7PtMFMMXjpYrOFZr/5edWpeaewsdecKB7ihUybpesIXGU51xEpnplP7UyNjA1vLg443/fGZF/aq6rP5ZeFgb0wRYMO+meJ0NLmDtRHoguKLhupmf+cNBVOn7lu6t3KFgpQabIkEgf4TOASl4kwBnFa7E4zrPvnKB5Yr6btAuWaR0QFkyNPDMMrsmb+Iv548bGw2tn35c2Q1ZcTIKEJ9QeTi2Pqa+Ph/yrXaECVj04jzrG4YOEMONHNMRV8xeWo+zvI/rRQW7jTJWpBKp4SxLWRF/0Awo7nPvlck2ddX17YPQyaZCaJcj0vaPXClK0Z+nfcy1z2yJ9l6ns2F9rmTNWHZsyrfG/ePaZiOb2jcxOjx+V+Wso0eMFkZqRAILcL0MqNN4xwIrfipkOvHwpuWS4+LR2YiELyok+qxdjjMcgkryRl5++MxUUbMpP8SA3vAitEkvuryRn5D5frOqp53Gei8+/4NxRw0Chp1gX0VW6zhylLXgggKOx8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
