appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 4YFelmBseFm/H8ZLabIUwXeOMQDRfqx+q9ywr4k+VJK9Nr/zdGENAuOiQT+es6aQ3HXiuKAqfDhiKhDF8dsBrtfZkO097hzva8dvSZjjv8Jlw7c2QrFkbrtNFD7ASw+gYec8BeD0/aIh3KZrmfF5sZ7sDx6/MJicn2ZYBy/4oZG8uXbFmfMA5pTnuuyJrJRvYmpQCav/Fo9sZSit3VOEC5Fp3uIkY+zbBQlEJQJdbLkFOUHy6VBrCzmVM7DHM21x62KdEsP9est8Oq9R20SV1PSxIOxo7PGLkaGFp5TsY0P58DfaiY32WXOgGcUEHehJEDHrUfwoLXLDBl0OPI9nMxFtMtetFkyJZZl95f+KuxOtfYSWzi3VL03r2CDo3GGVT+awoqf4K1BNbaqdu74bb6YAeXSRUzGZFhF7IfGX8BWrWLet/Qh46O/5/02G/m7R31A0D3iq8xbTs2fyE9jDUcA3xIQ5sAXeQzExH3dfomdDC9SMTUzUwS6weacPDDTDmqOWJVSR+90X+GQpv5qqmw1juydIdtUaeLccp+4TV/j9W9VhK8wBLxxAU5C1UAenlsJ5RpZt7GVlti1z9V3epFEwo/PM/YqzgPxdTD2+ZyfSS7c3KG/cseBaUqYOZP+Zaa9s0za+9bhAgxC5rg/XfXu0OCWdCxWhLm3T5/oqvto=}
