travis:
  secure:
    BINSTAR_TOKEN: Fio7puzaGAkGRbSCm9DtYYtCqM4pOFmCE+RJlCoyzrGI2cRawt/UmPdb8bfWtHUJ5C/DbYltuMoTxRdJ0dbJz7WcRkk+hL+z3W0sfpjcODHeZsYkHgfMnd2GPlziSpy/88ljPw6i7SuSFdrzLgPuOT0P0XYzMHPFFtscu07Kn34lwq0eBGfCeZN5SRE932Gz+q4O61v+fxg7YEDJi6VvEFSiFk9Kfc0yapuwhSjVkZGWbvsgjQV1mVjLFxwkLyj1Ao6ujy2pXUCyjsCv3uN+nx28yImmRUgJ5adH3TTyFI5496Z9RCkhXI2Bp47nK5OVpfLH1QEidf39USwavJp2HL63UTBhZx44TTSpNI27XJu9S0oVAF1KX6mq2KZ+iFOpPPTgx+0lPuBuvaCumuY72VPkEM0jOAVjGR715u9R7/e5ju8pmsglAIBkXA2nHBhIq7LE+0Z4dd3/opXz7bCP5CHvNJL8d64sfuUeq54k3OapAIWxGySDnVGFZYdCHR7ozua2YoGkaWhpEVu0XPNHexu6VuIZ7qQuIVFm9fCOfqq+RiLkAMhSCb8HUen3S63LM5r7EQBUzeX/UVgZajnRZYiEkDtMvtwT07dyEKZXrObRkfqLDoTcqJDSklmCSZjp2/gwTAYvn3ZlOcwFttDO3CB/9ALt0f9avSJ7bCaanno=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
