travis:
  secure:
    BINSTAR_TOKEN: pE0/vpvkSIuyxjzpgRZwB/cziinEg6S1mshsidOWXLmuTYxhgXBCckdhAJ0G2G8/JNLQ2JGYgUB03deomP98/d0TZ9ugNrlt3LDQOVoY7avfvJDFo1fiJqIwbH0PVaFDLPe2jFs5Pn3xGViYMw6CdQUecudjAV+e2Am5H/Vj54+iJnLZzj6S2scT8yYS4esR6Co7nzJ6ztyksk92BOsyqM9dxZRRtZSLLvrI4hzwcW5FkVuxkwEpnMuZ7YIkMTYyFjU7PZ1uH/HqXTMkS6PoqWTG6boUAQ0C1HVWJUt26QRwXbvFtc6Xa5k59RhDVYAkYUQuAzZ0N9xjaYXNsarRCq+jtqhqQfMtcSEWY4kmHPDFRTQR9NsyPDimMYyjrLlwhpj5bzlm9ow4bT/HLhMNVdi4MqzrwU9sLo7cmVxHCQkTkFTQ+y9Mpidcj5ZlvyPddVwApbN9GQhKTnLtTeYFjcQnRkrx2qtRqJvt3+ICZIprmZIuKGPFQrz06lDiBfUr2ZKrSvl0B1ZMnHWYW5cTl9DUKoQb8QNncrwYKfNazW+lZoT+Fp9utfkYJoqB3fukz3dXzTWzc5v59XjfSTkXJ6fpFk0pPzpQPbw82mJJGDtfZklZ4TNWgRT12l8SWAY9EuK8XsoZ+X+Ysw2PhK2rvCQiDMnxuIswQCvLO5hbTYc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
